lib/asciinema_admin/router.ex
defmodule AsciinemaAdmin.Router do
  use AsciinemaAdmin, :router
  import Oban.Web.Router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", AsciinemaAdmin do
    pipe_through :browser

    get "/", HomeController, :show
  end

  scope "/admin", AsciinemaAdmin do
    pipe_through :browser

    get "/", HomeController, :show
    get "/users/lookup", UserController, :lookup

    resources "/users", UserController do
      resources "/clis", CliController
    end

    live_dashboard "/dashboard", metrics: Asciinema.Telemetry
    oban_dashboard("/oban")
  end
end

lib/asciinema_web/router.ex
defmodule AsciinemaWeb.Router do
  use AsciinemaWeb, :router
  alias AsciinemaWeb.Plug.{Authn, TrailingFormat}

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Authn
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  pipeline :asciicast do
    plug TrailingFormat
    plug :accepts, ~w(html js json cast txt svg png gif)
    plug :format_specific_plugs
    plug :put_secure_browser_headers
  end

  pipeline :oembed do
    plug :accepts, ~w(json xml)
    plug :put_secure_browser_headers
  end

  pipeline :webfinger do
    plug :put_format, :json
  end

  pipeline :legacy do
    plug :assign_legacy_marker
  end

  scope "/", AsciinemaWeb do
    pipe_through :asciicast

    resources "/a", RecordingController, only: [:show, :edit, :update, :delete]
  end

  scope "/", AsciinemaWeb do
    pipe_through :oembed

    get "/oembed", OembedController, :show
  end

  scope "/", AsciinemaWeb do
    pipe_through :webfinger
    get "/.well-known/webfinger", WebFingerController, :show
  end

  scope "/", AsciinemaWeb do
    # Use the default browser stack
    pipe_through :browser

    get "/", RecordingController, :auto

    get "/explore", RecordingController, :auto, as: :explore
    get "/explore/featured", RecordingController, :featured, as: :explore
    get "/explore/public", RecordingController, :public, as: :explore

    get "/a/:id/iframe", RecordingController, :iframe
    get "/a/:id/example", RecordingController, :example

    resources "/s", StreamController, only: [:show, :edit, :update, :delete]

    resources "/login", LoginController, only: [:new, :create], singleton: true
    get "/login/sent", LoginController, :sent, as: :login

    resources "/user", UserController,
      as: :user,
      only: [:edit, :update, :delete],
      singleton: true do
      resources "/streams", StreamController, only: [:index, :create]
    end

    resources "/users", UserController, as: :users, only: [:new, :create]
    get "/u/:id", UserController, :show
    get "/~:username", UserController, :show
    get "/u/:id/avatar", AvatarController, :show
    get "/user/delete", UserController, :delete, as: :user_deletion

    resources "/username", UsernameController, only: [:new, :create], singleton: true
    get "/username/skip", UsernameController, :skip, as: :username

    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    get "/connect/:install_id", CliController, :register, as: :connect

    resources "/clis", CliController, only: [:delete]

    get "/about", PageController, :about
  end

  scope "/api", AsciinemaWeb.Api, as: :api do
    pipe_through :api

    scope "/v1" do
      resources "/recordings", RecordingController, only: [:create, :update, :delete]
      resources "/streams", StreamController, only: [:create, :update, :delete]

      scope "/user" do
        get "/streams", StreamController, :index
      end
    end

    # used by CLI 2.x
    post "/asciicasts", RecordingController, :create

    scope "/" do
      # used by CLI 3.0 RC.5 and earlier
      # remove after release of the final CLI 3.0
      pipe_through :legacy

      post "/streams", StreamController, :create
      get "/user/streams/:id", StreamController, :show
    end
  end

  if Application.compile_env(:asciinema, :dev_routes) do
    scope "/dev" do
      pipe_through :browser
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  defp format_specific_plugs(conn, []) do
    conn
    |> fetch_session([])
    |> Authn.call([])
    |> format_specific_plugs(get_format(conn))
  end

  defp format_specific_plugs(conn, "html") do
    conn
    |> fetch_flash([])
    |> protect_from_forgery([])
  end

  defp format_specific_plugs(conn, _other), do: conn

  defp assign_legacy_marker(conn, []) do
    assign(conn, :legacy_path, true)
  end
end

lib/asciinema_admin/components/layouts.ex
defmodule AsciinemaAdmin.Layouts do
  @moduledoc """
  This module holds different layouts used by your application.

  See the `layouts` directory for all templates available.
  The "root" layout is a skeleton rendered as part of the
  application router. The "app" layout is set as the default
  layout on both `use AsciinemaAdmin, :controller` and
  `use AsciinemaAdmin, :live_view`.
  """
  use AsciinemaAdmin, :html

  embed_templates "layouts/*"
end

lib/asciinema_web/views/layout_view.ex
defmodule AsciinemaWeb.LayoutView do
  use AsciinemaWeb, :view
  import AsciinemaWeb.UserHTML, only: [avatar_url: 1]

  def page_title(conn) do
    title = conn.assigns[:page_title] || "Record and share your terminal sessions, the simple way"

    "#{title} - #{conn.host}"
  end

  def body_class(conn) do
    action = Phoenix.Controller.action_name(conn)

    controller =
      conn
      |> Phoenix.Controller.controller_module()
      |> Atom.to_string()
      |> String.replace(~r/(Elixir\.AsciinemaWeb\.)|(Controller)/, "")
      |> String.replace(".", "")
      |> Inflex.underscore()
      |> String.replace("_", " ")
      |> Inflex.parameterize()

    "c-#{controller} a-#{action}"
  end
end

lib/asciinema_web/templates/layout/_flash.html.eex
<%= if message = get_flash(@conn, :info) do %>
  <section class="flash notice"><div class="container"><%= message %></div></section>
<% end %>

<%= if message = get_flash(@conn, :error) do %>
  <section class="flash alert"><div class="container"><%= message %></div></section>
<% end %>

lib/asciinema_web/templates/layout/_footer.html.eex
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xs-12">
        <ul class="links">
          <li><a href="<%= Routes.page_path(@conn, :contributing) %>">Contributing</a></li>
          <li><a href="<%= Routes.page_path(@conn, :tos) %>">Terms of Service</a></li>
          <li><a href="<%= Routes.page_path(@conn, :privacy) %>">Privacy Policy</a></li>
          <li><a href="<%= Routes.page_path(@conn, :contact) %>">Contact</a></li>
        </ul>
      </div>

      <div class="col-md-4 col-xs-12 text-center">
        <span>
          Sponsored by
          <br/>
          <a class="brightbox-logo" href="http://brightbox.com/" rel="nofollow">
            <img src="<%= Routes.static_path(@conn, "/images/brightbox.png") %>" />
          </a>
        </span>
      </div>

      <div class="col-md-4 col-xs-12">
        <ul class="links float-right">
          <li>
            <b>forum:</b> <a href="https://discourse.asciinema.org">discourse.asciinema.org</a>
          </li>
          <li>
            <b>irc:</b> <a href="https://web.libera.chat/gamja/#asciinema">#asciinema on Libera.Chat</a>
          </li>
          <li>
              <b>matrix:</b> <a href="https://matrix.to/#/#asciinema:matrix.org">#asciinema:matrix.org</a>
          </li>

          <li>
            <b>twitter:</b> <a href="https://twitter.com/asciinema" title="Follow @asciinema on Twitter">@asciinema</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

lib/asciinema_web/templates/layout/_header.html.eex
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path() %>">
        <img src="<%= Routes.static_path(@conn, "/images/logo-red.svg") %>">
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= Routes.explore_path(@conn, :auto) %>">Explore</span></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= Routes.doc_path(@conn, :show, :"getting-started") %>">Record</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%= Routes.doc_path(@conn, :show, :"how-it-works") %>">Docs</a>
          </li>
        </ul>

        <ul class="navbar-nav navbar-right session-info">
          <%= if @current_user do %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">

                <img class="avatar" src="<%= avatar_url(@current_user) %>"><%= @current_user.username || @current_user.email %>
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="<%= profile_path(@current_user) %>">Profile</a>
                <a class="dropdown-item" href="<%= Routes.user_path(@conn, :edit) %>">Settings</a>
                <%= link "Log out", to: Routes.session_path(@conn, :delete), class: "dropdown-item logout", method: :delete %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= Routes.login_path(@conn, :new) %>" id="log-in">
                Log in
                <%= if sign_up_enabled?(@conn) do %> / Sign up<% end %>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

lib/asciinema_web/templates/layout/_header.html.heex
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href={~p"/"}>
        <img src={Routes.static_path(@conn, "/images/logo-red.svg")} />
      </a>

      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="https://docs.asciinema.org/getting-started/">
              Get started
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href={~p"/explore"}>Explore</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="https://docs.asciinema.org/">Docs</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="https://discourse.asciinema.org/">Forum</a>
          </li>
        </ul>

        <ul class="navbar-nav navbar-right session-info">
          <li :if={@current_user} class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
              <img class="avatar" src={avatar_url(@current_user)} />{@current_user.username ||
                @current_user.email}
            </a>
            <div class="dropdown-menu">
              <%= if @current_user.streaming_enabled do %>
                <a href={~p"/user/streams"} class="dropdown-item">
                  <strong>Stream</strong>
                </a>
                <div class="dropdown-divider"></div>
              <% end %>

              <a href={profile_path(@current_user)} class="dropdown-item">Profile</a>
              <a href={~p"/user/edit"} class="dropdown-item">Settings</a>
              <div class="dropdown-divider"></div>

              <.link href={~p"/session"} class="dropdown-item logout" method="delete">
                Log out
              </.link>
            </div>
          </li>

          <li :if={!@current_user} class="nav-item">
            <a href={~p"/login/new"} class="nav-link" id="log-in">
              Log in
              <%= if sign_up_enabled?() do %>
                / Sign up
              <% end %>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

lib/asciinema_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title><%= page_title @conn %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <link rel="shortcut icon" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>">
    <%= render_existing view_module(@conn), "meta." <> view_template(@conn), assigns %>
  </head>

  <body class="l-app <%= body_class(@conn) %>">
    <%= render "_header.html", conn: @conn, current_user: @current_user %>
    <%= render "_flash.html", conn: @conn %>

    <main role="main" class="<%= main_class(@conn) %>">
      <%= @inner_content %>
    </main>

    <%= render "_footer.html", conn: @conn %>
    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/asciinema_web/templates/layout/app.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <meta name="csrf-token" content={Plug.CSRFProtection.get_csrf_token()} />
    <title>{page_title(@conn)}</title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <link rel="shortcut icon" href={Routes.static_path(@conn, "/images/favicon.png")} />

    <%= if function_exported?(view_module(@conn), :head, 2) do %>
      {view_module(@conn).head(view_template(@conn), assigns)}
    <% end %>
  </head>

  <body class={"l-app " <> body_class(@conn)}>
    {render("_header.html", conn: @conn, current_user: @current_user)}
    {render("_flash.html", flash: @flash)}

    <main role="main">
      {@inner_content}
    </main>

    {render("_footer.html", conn: @conn)}
    <script>
      window.__asciinema__workerUrl = '<%= Routes.static_path(@conn, "/js/player-worker.min.js") %>';
    </script>
    <script phx-track-static src={Routes.static_path(@conn, "/assets/app.js")}>
    </script>
  </body>
</html>

lib/asciinema_web/templates/layout/docs.html.eex
<%= render_layout AsciinemaWeb.LayoutView, "app.html", assigns do %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render AsciinemaWeb.DocView, "topics.html", conn: @conn, active_topic: @topic %>
      </div>
      <div class="col-md-9 content">
        <%= @inner_content %>
      </div>
    </div>
  </div>
<% end %>

lib/asciinema_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>

lib/asciinema_web/templates/layout/email.html.heex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    {@inner_content}
  </body>
</html>

lib/asciinema_web/templates/layout/example.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="light dark" />

    <style>
      body {
        font-family: 'Fira Sans', sans-serif;
        margin: 20px;
        color: #334;
      }

      .content {
        background-color: #dde;
        padding: 20px;
        max-width: 960px;
      }

      p { font-size: 16px }

      @media (prefers-color-scheme: dark) {
        body {
          color: #dde;
        }

        .content {
          background-color: #334;
        }
      }
    </style>
  </head>

  <body>
    <div class="content">
      {@inner_content}
    </div>
  </body>
</html>

lib/asciinema_web/templates/layout/iframe.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/iframe.css") %>">
  </head>

  <body class="iframe">
    <%= @inner_content %>
    <script src="<%= Routes.static_path(@conn, "/js/iframe.js") %>"></script>
  </body>
</html>

lib/asciinema_web/templates/layout/iframe.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="light dark" />
    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/iframe.css")} />
  </head>

  <body class="iframe">
    {@inner_content}
    <script>
      window.__asciinema__workerUrl = '<%= Routes.static_path(@conn, "/js/player-worker.min.js") %>';
    </script>
    <script src={Routes.static_path(@conn, "/assets/iframe.js")}>
    </script>
  </body>
</html>

lib/asciinema_web/templates/layout/simple.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= page_title @conn %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
    <link rel="shortcut icon" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>">
    <!-- google analytics -->
    <!-- content for head (twitter, open graph tags) -->
  </head>

  <body class="simple-layout">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= @inner_content %>
        </div>
      </div>
    </div>
  </body>
</html>

lib/asciinema_web/templates/layout/simple.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{page_title(@conn)}</title>
    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <link rel="shortcut icon" href={Routes.static_path(@conn, "/images/favicon.png")} />
  </head>

  <body class="simple-layout">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {@inner_content}
        </div>
      </div>
    </div>
  </body>
</html>